# Generated by Django 3.0.2 on 2020-03-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tbooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Booking',
            new_name='Booking_date',
        ),
    ]
